AWSTemplateFormatVersion: 2010-09-09

Description: >
  Creates an AWS IAM OIDC identity provider, role, and policies for use with GitHub OIDC.

Parameters:
  GithubActionsThumbprint:
    Type: CommaDelimitedList
    Default: 6938fd4d98bab03faadb97b34396831e3780aea1
    Description: >
      Comma seperated list of valid server thumbprints for tokens sent by the GitHub OIDC provider
      Default comes from https://github.blog/changelog/2022-01-13-github-actions-update-on-oidc-based-deployments-to-aws/
  AudienceList:
    Type: CommaDelimitedList
    Default: sts.amazonaws.com
    Description: >
      Comma-seperated list of allowed audiences for tokens sent by the GitHub OIDC provider
      Default is the audience for the official AWS credentials action: https://github.com/aws-actions/configure-aws-credentials
  SubjectClaimFilters:
    Type: CommaDelimitedList
    Description: >
      Subject claim filter for valid tokens sent by the GitHub OIDC provider
  ManagedPolicyARNs:
    Type: CommaDelimitedList
    Default: ""
    Description: Comma-separated list of ARNs for managed IAM policies to attach to the GitHub OIDC role
  GitHubActionsAllowedAWSActions:
    Type: CommaDelimitedList
    Default: ""
    Description: >
      Comma-separated list of AWS service actions that GitHub Actions are allowed to perform via the GitHub OIDC role

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "AWS IAM OIDC Provider Configuration Info"
        Parameters:
          - SubjectClaimFilters
          - GithubActionsThumbprint
          - AudienceList
      - Label:
          default: "AWS IAM Permission Info"
        Parameters:
          - ManagedPolicyARNs
          - GitHubActionsAllowedAWSActions

Conditions:
  CreateGitHubActionsPermissionsPolicy: !Not
    - !Equals
      - !Join ["", !Ref GitHubActionsAllowedAWSActions]
      - ""
  AttachMangagedPolicyARNs: !Not
    - !Equals
      - !Join ["", !Ref ManagedPolicyARNs]
      - ""

Resources:
  GitHubIdentityProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ThumbprintList: !Ref GithubActionsThumbprint
      ClientIdList: !Ref AudienceList
  GitHubActionsPermissions:
    Type: AWS::IAM::Policy
    Condition: CreateGitHubActionsPermissionsPolicy
    Properties:
      PolicyName: GitHubActionsPermissions
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: !Ref GitHubActionsAllowedAWSActions
            Resource: "*"
      Roles:
        - Ref: "GitHubActionsServiceRole"
  GitHubActionsServiceRole:
    Type: AWS::IAM::Role
    Description: Service Role for GitHub OIDC
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: RoleForGitHubOIDC
            Effect: Allow
            Principal:
              Federated: !GetAtt GitHubIdentityProvider.Arn
            Action:
              - "sts:AssumeRoleWithWebIdentity"
            Condition:
              StringEquals:
                "token.actions.githubusercontent.com:aud": !Ref AudienceList
              StringLike:
                "token.actions.githubusercontent.com:sub": !Ref SubjectClaimFilters
      ManagedPolicyArns: !If
        - AttachMangagedPolicyARNs
        - !Ref ManagedPolicyARNs
        - !Ref AWS::NoValue
      # path and permissions boundary as required per https://cloud.cms.gov/creating-identity-access-management-policies
      Path: "/delegatedadmin/developer/"
      PermissionsBoundary: !Sub "arn:aws:iam::${AWS::AccountId}:policy/cms-cloud-admin/developer-boundary-policy"

Outputs:
  ServiceRoleARN:
    Description: ARN of the service role for GitHub OIDC
    Value: !GetAtt GitHubActionsServiceRole.Arn
