name: Run security scans

on:
  push:
    branches:
      - bharvey-test-jwt

permissions:
  id-token: write

jobs:
 test:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3

    - uses: ben-harvey/configure-aws-credentials@master
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::${{ secrets.DEV_AWS_ACCOUNT_ID }}:role/delegatedadmin/developer/github-oidc-GitHubActionsServiceRole-TREPDPZ0TY0J

    - run: aws s3api list-buckets

    - name: upload
      if: always()
      uses: actions/upload-artifact@v1
      with:
        name: token.txt
        path: token.txt
