name: Get latest GitHub Actions Runner

on:
  push:
    branches:
      - bharvey-fix-ci
  schedule:
    - cron: "40 18 * * *"
jobs:
  update-runner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set release version and current version variables
        id: get-versions
        run: |
          echo ::set-output name=current_tag::$(grep ACTIONS_VERSION Dockerfile | cut -d'=' -f 2 | sed -e 's/^"//' -e 's/"$//')
          echo ::set-output name=release_tag::$(curl -sL https://api.github.com/repos/actions/runner/releases/latest | jq -r ".tag_name[1:] | tostring")

      - name: Change release version in Dockerfile
        if: ${{ steps.get-versions.outputs.release_tag != steps.get-versions.outputs.current_tag }}
        id: update-version
        env:
          OLD_VERSION: ${{ steps.get-versions.outputs.current_tag }}
          NEW_VERSION: ${{ steps.get-versions.outputs.release_tag }}
        run: |
          sed -i --expression='s,"'"$OLD_VERSION"'","'"$NEW_VERSION"'",g' Dockerfile

      - name: Create Pull Request
        if: ${{ steps.get-versions.outputs.release_tag != steps.get-versions.outputs.current_tag }}
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.BHARVEY_GITHUB_TOKEN }}
          commit-message: Update actions runner to new version
          author: robot-mac-fc <robot-mac-fc@users.noreply.github.com>
          branch: update-actions-runner-to-${{ steps.get-versions.outputs.release_tag }}
          delete-branch: true
          title: Update Actions Runner Version to ${{ steps.get-versions.outputs.release_tag }}
          body: |
            Automated update from Github Actions Runner version ${{ steps.get-versions.outputs.current_tag }} to version ${{ steps.get-versions.outputs.release_tag }}
            Release Notes: https://github.com/actions/runner/releases/tag/v${{ steps.get-versions.outputs.release_tag }}
          team-reviewers: MAC-FC
